dw-prj2-grp1-caia-master/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
	path('signup/', views.signUpPage, name="signup"),
	path('login/', views.loginPage, name="login"),
	path('logout/', views.logoutUser, name="logout"),
	path('account/', views.accountManagementPage, name="account"),
	path('account/change-password', views.changePassword, name="change-password"),
	path('account/items', views.AccountItemListView.as_view(), name="account-item-list"), 
]

dw-prj2-grp1-caia-master/blog/urls.py
from django.urls import path
from . import views

#urls for blog
app_name = "blog"
urlpatterns = [
	path('<int:pk>/', views.BlogView.as_view(), name="blog"),
	path('<int:blog_id>/add-entry/', views.AddEntryView, name="add-entry"),
]

dw-prj2-grp1-caia-master/item_management/urls.py
from django.urls import path, re_path
from .views import (
    ItemDeleteView,
    itemCreateView,
    itemUpdateView,
    ItemDetailView,
    ItemListView,
    upvote,
    comment,
    ItemBuyView,
    flag
)

app_name = "item_management"
urlpatterns = [
    path('', ItemListView.as_view(), name='item-list'),
    re_path(r'^(?P<search>\w+)$', ItemListView.as_view(), name='item-list'),
    path('<int:id>/', ItemDetailView.as_view(), name='item-detail'),
    path('create/', itemCreateView, name='item-create'),
    path('<int:id>/update/', itemUpdateView, name='item-update'),
    path('<int:id>/delete/', ItemDeleteView.as_view(), name='item-delete'),
    path('<int:id>/upvote/', upvote, name='upvote'),
    path('<int:id>/comment/', comment, name='comment'),
    path('<int:id>/buy/', ItemBuyView.as_view(), name='buy'),
    path('<int:id>/flag/', flag, name='flag')
]

dw-prj2-grp1-caia-master/kijijiwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('item/', include('item_management.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls')),
]

dw-prj2-grp1-caia-master/kijijiwebsite/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from database.models import Item


class HomeView(generic.ListView):
    """
    Home view of the web page displaying a list of items
    """
    model = Item
    template_name = 'home/home.html'

dw-prj2-grp1-caia-master/kijijiwebsite/templates/base/base.html
{# base.html template. All if not most the templates will extend this html #}
<div id="site-header">
  <header>
    <h1 class="header-element">Kijiji Project</h1>
    <form action="/item" method="get">
      {% csrf_token %}
      <input type="text" name="search" maxlength="200" value="">
      <input class="header-element" type="submit" value="Search">
    </form>
  </header>
  <nav class="header-element">
    <a href="{% url 'home' %}" class="link-button">Home</a>
    {% if user.is_authenticated %}
        <a href="{% url 'accounts:account' %}" class="link-button">Account</a>
        {% if user.customer.blog.id %}
            <a href="{% url 'blog:blog' user.customer.blog.id %}" class="link-button">Blog</a>
        {% endif %}
        <a href="{% url 'accounts:logout' %}" class="link-button">Logout</a>
        <a href="{% url 'item_management:item-create' %}" class="link-button">Create Item</a>
    {% else %}
        <a href="{% url 'accounts:login' %}" class="link-button">Login</a>
        <a href="{% url 'accounts:signup' %}" class="link-button">Sign Up</a>
    {% endif %}
  </nav>
  {% block page_title %}
  {% endblock %}
</div>
<div id="center-page">
  {% block center_page %}
  {% endblock %}
</div>
<footer>
  <p>Django Project made by Alin Serban Caia, Anthony Painchaud, Asli Zeybek and Susan Vuu</p>
</footer>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}">