dw-prj2-grp1-caia-master/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
	path('signup/', views.signUpPage, name="signup"),
	path('login/', views.loginPage, name="login"),
	path('logout/', views.logoutUser, name="logout"),
	path('account/', views.accountManagementPage, name="account"),
	path('account/change-password', views.changePassword, name="change-password"),
	path('account/items', views.AccountItemListView.as_view(), name="account-item-list"), 
]

dw-prj2-grp1-caia-master/blog/urls.py
from django.urls import path
from . import views

#urls for blog
app_name = "blog"
urlpatterns = [
	path('<int:pk>/', views.BlogView.as_view(), name="blog"),
	path('<int:blog_id>/add-entry/', views.AddEntryView, name="add-entry"),
]

dw-prj2-grp1-caia-master/item_management/urls.py
from django.urls import path, re_path
from .views import (
    ItemDeleteView,
    itemCreateView,
    itemUpdateView,
    ItemDetailView,
    ItemListView,
    upvote,
    comment,
    ItemBuyView,
    flag
)

app_name = "item_management"
urlpatterns = [
    path('', ItemListView.as_view(), name='item-list'),
    re_path(r'^(?P<search>\w+)$', ItemListView.as_view(), name='item-list'),
    path('<int:id>/', ItemDetailView.as_view(), name='item-detail'),
    path('create/', itemCreateView, name='item-create'),
    path('<int:id>/update/', itemUpdateView, name='item-update'),
    path('<int:id>/delete/', ItemDeleteView.as_view(), name='item-delete'),
    path('<int:id>/upvote/', upvote, name='upvote'),
    path('<int:id>/comment/', comment, name='comment'),
    path('<int:id>/buy/', ItemBuyView.as_view(), name='buy'),
    path('<int:id>/flag/', flag, name='flag')
]

dw-prj2-grp1-caia-master/kijijiwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('item/', include('item_management.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls')),
]

dw-prj2-grp1-caia-master/item_management/models.py
from django.db import models

# Create your models here.

dw-prj2-grp1-caia-master/item_management/forms.py
from django import forms

from database.models import Item, Comment


class ItemModelForm(forms.ModelForm):
    """
    Form used to create or udpate an item
    """
    price = forms.DecimalField(max_digits=10, decimal_places=2)
    item_name = forms.CharField(max_length=200, widget=forms.TextInput(
        attrs={"placeholder": "Your item name"}))
    description = forms.CharField(widget=forms.Textarea(
        attrs={"placeholder": "Your description"}))
    image = forms.ImageField(required=False)

    class Meta:
        model = Item
        fields = [
            'price',
            'item_name',
            'description',
            'image',
        ]


class CommentModelForm(forms.ModelForm):
    """
    Form used to add a a comment
    """
    comment_text = forms.CharField(label='', widget=forms.Textarea(
        attrs={"placeholder": "Your comment"}))

    class Meta:
        model = Comment
        fields = [
            'comment_text'
        ]

dw-prj2-grp1-caia-master/item_management/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.shortcuts import redirect
from django.views.generic import (
    DeleteView,
    DetailView,
    ListView,
)

from datetime import datetime
from .forms import ItemModelForm, CommentModelForm
from django.db.models import Q
from database.models import Item, user_directory_path, Comment, CustomerVote


def itemCreateView(request):
    """
    View used to create an item
    """
    if request.user.is_authenticated == False:
        # Redirect to login if user is not authenticated
        return redirect('accounts:login')
    else:
        # Create empty form
        form = ItemModelForm()
        # POST request
        if request.method == 'POST':
            form = ItemModelForm(request.POST, request.FILES)
            if form.is_valid():
                # Saving item to database
                new_item = Item(
                    owner=request.user.customer,
                    price=form.cleaned_data.get('price'),
                    item_name=form.cleaned_data.get('item_name'),
                    description=form.cleaned_data.get('description'),
                    image=form.cleaned_data.get('image'),
                )
                new_item.save()

    # Returning to form if it was invalid
    context = {'form': form}
    return render(request, 'item_management/item_create.html', context)


def itemUpdateView(request, **kwargs):
    """
    View used to update an item
    """
    if request.user.is_authenticated == False:
        # Redirect to login if user is not authenticated
        return redirect('accounts:login')
    else:
        # Retrieving item, can throw 404 if object doens't belong to customer
        item = get_object_or_404(Item, id=kwargs.get(
            "id"), owner=request.user.customer)
        form = ItemModelForm(instance=item)
        # POST request
        if request.method == 'POST':
            form = ItemModelForm(request.POST, request.FILES, instance=item)
            if form.is_valid():
                # Updating item
                form.save()

                # Updating image if a new one was provided and it's not the old one
                new_image = form.cleaned_data.get('new_image'),
                if new_image is not None and new_image[0] != item.image:
                    item.image = new_image[0]
                    item.save()

    # Returning to form if it was invalid
    context = {'form': form}
    return render(request, 'item_management/item_update.html', context)


class ItemDeleteView(DeleteView):
    """
    View used to delete an item
    """
    template_name = 'item_management/item_delete.html'

    def get_object(self):
        """
        Retrieves the item to delete
        """
        if self.request.user.is_authenticated:
            id = self.kwargs.get("id")
            # Returning object, 404 if it doesn't exist or doesn't belong to customer
            return get_object_or_404(Item, id=id, owner__user=self.request.user)
        return None

    def get_success_url(self):
        """
        Redirects user to home page when deletion is finished
        """
        return reverse("home")


class ItemDetailView(DetailView):
    """
    Detail view used to show an item's iformation
    """
    template_name = 'item_management/item_detail.html'

    def get_object(self):
        """
        Retrieves the item to diplsay
        """
        return get_object_or_404(Item, pk=self.kwargs.get("id"))

    def get_context_data(self, *args, **kwargs):
        """
        Provides context data to template
        """
        # Retrieving the item's commments
        context = super(ItemDetailView, self).get_context_data(*args, **kwargs)
        context['comments'] = Comment.objects.filter(
            item__pk=self.kwargs.get("id"))

        # Retrieving the user's vote on this item, empty if he never like it
        context['customervote'] = CustomerVote.objects.filter(
            item__pk=self.kwargs.get("id"))
        return context


class ItemListView(ListView):
    """
    List view of items
    """
    template_name = 'item_management/item_list.html'

    def get_queryset(self):
        """
        Retrieves the list of items to display
        """
        # Retrieving url query if there is one to search for items with a certain
        # substring in its title or the owner's username
        if self.request.method == 'GET' and 'search' in self.request.GET:
            return Item.objects.filter(Q(item_name__icontains=self.request.GET['search']) | Q(owner__user__username__icontains=self.request.GET['search']))
        else:
            return Item.objects.all()


class ItemBuyView(DeleteView):
    """
    View used to buy an item
    """
    template_name = 'item_management/item_buy.html'

    def get_object(self):
        """
        Retrieves the item to buy
        """
        if self.request.user.is_authenticated:
            id = self.kwargs.get("id")
            item = get_object_or_404(
                Item, ~Q(owner=self.request.user.customer), id=id)
            return item
        return None

    def get_success_url(self):
        """
        Returns to home page when user has bought item
        """
        id = self.kwargs.get("id")
        item = Item.objects.get(id=id)
        self.request.user.customer.account_cost -= item.price
        self.request.user.customer.save()

        return reverse("home")


def upvote(request, id):
    """
    View used to upvote an item
    """
    # Retrieving item
    item = get_object_or_404(Item, pk=id)
    # Making sure user is authenticated
    if request.user.is_authenticated:
        # Retrieving the user's vote on this item, empty if he never like it
        customer_vote = CustomerVote.objects.filter(
            customer=request.user.customer).filter(item=item)
        if customer_vote.exists():
            # If user had already voted, we remove his vote
            item.votes -= 1
            customer_vote.delete()
        else:
            # Adding vote
            item.votes += 1
            new_vote = CustomerVote(customer=request.user.customer, item=item)
            new_vote.save()
        item.save()
        # Going back to the item detail view
        return redirect('../')
    else:
        return redirect('accounts:login')


def comment(request, **kwargs):
    """
    View used to comment on an item
    """
    if request.user.is_authenticated == False:
        return redirect('home')
    else:
        form = CommentModelForm()
        if request.method == 'POST':
            form = CommentModelForm(request.POST, request.FILES)
            if form.is_valid():
                new_comment = Comment(
                    item=get_object_or_404(Item, pk=kwargs.get("id")),
                    comment_text=form.cleaned_data.get('comment_text'),
                    author=request.user.customer,
                    comment_date=datetime.today()
                )
                new_comment.save()
                return redirect('../')

    context = {'form': form}
    return render(request, 'item_management/item_comment.html', context)


def flag(request, id):
    """
    View used to flag an item
    """
    item = get_object_or_404(Item, pk=id)
    if request.user.is_authenticated:
        item.flags += 1

        item.save()
        return redirect('../')
    else:
        return redirect('accounts:login')

dw-prj2-grp1-caia-master/item_management/templates/item_management/item_buy.html
{% extends "../base/base.html" %}
{% block center_page %}
<form action='.' method='POST'>{% csrf_token %}
  {% if object.price < user.customer.account_cost %}
  <h1>Do you want to buy the item "{{ object.item_name }}"?</h1>
  <p>You have {{user.customer.account_cost}}$ and this costs {{object.price}}$</p>
  <p><input type='submit' value='Yes' /> <a href='../'>Cancel</a></p>

  {% else %}
  <p>You cannot afford this item at {{object.price}}$ with {{user.customer.account_cost}}$</p>
  {% endif%}

</form>
{% endblock %}

dw-prj2-grp1-caia-master/item_management/templates/item_management/item_comment.html
{% extends "../base/base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}">

{% block center_page %}
<form action='.' method='POST'>{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Save' />
</form>
{% endblock %}

dw-prj2-grp1-caia-master/item_management/templates/item_management/item_create.html
{% extends "../base/base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}">

{% block center_page %}
<form action='.' method='POST' enctype="multipart/form-data">{% csrf_token %}
  {{ form.as_p }}
  <input type='submit' value='Save' />
</form>
{% endblock %}

dw-prj2-grp1-caia-master/item_management/templates/item_management/item_delete.html
{% extends "../base/base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}">

{% block center_page %}
<form action='.' method='POST'>{% csrf_token %}
  <h1>Do you want to delete the item "{{ object.item_name }}"?</h1>
  <p><input type='submit' value='Yes' /> <a href='../'>Cancel</a></p>

</form>
{% endblock %}

dw-prj2-grp1-caia-master/item_management/templates/item_management/item_detail.html
{% extends "../base/base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}">

{% block center_page %}
<div>
  Owner: {{object.owner}}
</div>

<div>
  price:{{object.price}}$
</div>

<div>
  item name: {{object.item_name}}
</div>

<div>
  description: {{object.description}}
</div>

<div>
  {% if object.image %}
  <img src="{% static object.image.url %}" alt="Item picture">

  {% else %}

  <img src="{% static 'images/no-item.png' %}" alt="Item picture">
  {% endif%}
</div>

<div>
  {% if user.is_authenticated %}

  {% if object.owner != user.customer %}
  <a href="{% url 'item_management:buy' id=object.id %}">Buy it</a>
  {% endif %}

  {% else %}
  <a href="{% url 'accounts:login' %}">Buy it</a>
  {% endif %}
</div>

<div>
  {{object.votes}} like{{ object.votes|pluralize }}

  {% if user.is_authenticated %}

  {% if customervote.first.customer == user.customer %}
  <a href="{% url 'item_management:upvote' id=object.id %}">Unlike</a>

  {% else %}
  <a href="{% url 'item_management:upvote' id=object.id %}">Like</a>
  {% endif %}

  {% else %}
  <a href="{% url 'accounts:login' %}">Like</a>
  {% endif %}
</div>

<div>
  {% if user.is_authenticated %}
  {% if object.flags > 0 %}
  <p style="color:red;">Flagged (only removable by an admin)</p>

  {% else %}
  <a href="{% url 'item_management:flag' id=object.id %}">Flag</a>
  {% endif %}

  {% elif object.flags < 1 %}
  <a href="{% url 'accounts:login' %}">Flag</a>
  {% endif %}
</div>

<div>
  {% if user.is_authenticated and object.owner == user.customer %}
  <a href="{% url 'item_management:item-update' id=object.id %}">Update</a>
  <a href="{% url 'item_management:item-delete' id=object.id %}">Delete</a>
  {% endif %}
</div>

<div>
  {% if user.is_authenticated %}
  <a href="{% url 'item_management:comment' id=object.id %}">Comment</a>
  {% else %}
  Comment
  {% endif %}

  {% if comments %}
  <p>Comments:</p>
  <ul id="detail_ul">
    {% for comment in comments %}
    <li>{{comment}} ({{comment.comment_date}})</li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No comments</p>
  {% endif %}
</div>

{% endblock %}

dw-prj2-grp1-caia-master/item_management/templates/item_management/item_list.html
{% extends "../base/base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}">

{% block center_page %}
<ul>
  {% for instance in object_list %}
  <li>{% if instance.image %}
    <img src="{% static instance.image.url %}" alt="Item picture">
    {% else %}
    <img src="{% static 'images/no-item.png' %}" alt="Item picture">
    {% endif %} - Owner: {{instance.owner}} - item name: {{instance.item_name}} - price:{{instance.price}}$ - {{instance.votes}} like{{ instance.votes|pluralize }} - <a href="{{instance.get_absolute_url}}">Detail</a></li>
  <hr>
  {% endfor %}
</ul>
{% endblock %}

dw-prj2-grp1-caia-master/item_management/templates/item_management/item_update.html
{% extends "../base/base.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}">

{% block center_page %}
<form action='.' method='POST' enctype="multipart/form-data">
  <hr>
  {% if form.instance.image %}
  <img src="{% static form.instance.image.url %}" alt="Item picture">

  {% else %}

  <img src="{% static 'images/no-item.png' %}" alt="Item picture">
  {% endif%}
  <hr>
  {% csrf_token %}
  {{ form.as_p }}
  <hr>
  <input type='submit' value='Save' />
</form>
{% endblock %}